devcontainer: update scripts

diff --git a/.devcontainer/base/I b/.devcontainer/base/I
--- a/.devcontainer/base/I
+++ b/.devcontainer/base/I
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+set -euo pipefail
+shopt -qs lastpipe
 
 declare -ar CURL=(
   curl
@@ -8,8 +10,27 @@ declare -ar CURL=(
   --silent
 )
 
+RED=$'\e[1;31m' SGR0=$'\e[m'
+if [[ ${NO_COLOR:-} ]]; then
+  RED='' SGR0=''
+fi
+
+die() {
+  local -i code=1
+  if [[ $1 =~ ^[0-9]+$ ]]; then
+    code="$1"; shift
+  fi
+
+  local fmt="${1:?}"; shift || :
+
+  # shellcheck disable=SC2059
+  printf "${RED}error${SGR0}: ${fmt}\n" "$@" >&2
+
+  exit "$code"
+}
+
 create_user() {
-  local username="${1:?missing username}"
+  local username="${1:?add user: missing username}"
   local OPT OPTARG password comment="${username@u}"
   local -i OPTIND OPTERR=0
 
@@ -22,20 +43,21 @@ create_user() {
   done; shift $(( OPTIND - 1 ))
 
   useradd --create-home --comment="$comment" --user-group "$username"
-  if [[ $password ]]; then
+  if [[ ${password:-} ]]; then
     set_password "$username" "$password"
   fi
 }
 
 set_password() {
-  local username="${1:?missing username}"
+  local username="${1:?set password: missing username}"
   local password="${2:-$username}"
 
   yes "$password" | passwd -q "$username" || :
 }
 
 add_apt_key() {
-  local filename="${1:?}" url="${2:?}"
+  local filename="${1:?add key: missing key filename}"
+  local url="${2:?add key: missing key URL}"
   local key="$APT_KEYRINGS/$filename.gpg"
 
   sudo install -m 0755 -d "$APT_KEYRINGS"
@@ -46,7 +68,7 @@ add_apt_key() {
 }
 
 add_source_list() {
-  local filename="${1:?missing source list filename}"; shift
+  local filename="${1:?add source-list: missing source list filename}"; shift
   local OPT OPTARG key
   local -i OPTIND=1 OPTERR=0
   local -a options=("arch=$(dpkg --print-architecture)")
@@ -98,13 +120,13 @@ install_packages() {
 }
 
 fetch() {
-  local url="${1:?missing URL}"; shift
+  local url="${1:?fetch: missing URL}"; shift
   local dir='' filename=''
 
   while (( $# )); do
     case $1 in
-      as) filename="${2:?missing filename}" ;;
-      to) dir="${2:?missing path}" ;;
+      as) filename="${2:?fetch: missing filename}" ;;
+      to) dir="${2:?fetch: missing path}" ;;
     esac; shift 2
   done
 
@@ -119,9 +141,9 @@ fetch() {
 }
 
 fetch_github_release() {
-  local repo="${1:?missing repository name}"
-  local version="${2:?missing version}"
-  local pattern="${3:?missing asset filename pattern}"
+  local repo="${1:?fetch release: missing repository name}"
+  local version="${2:?fetch release: missing version}"
+  local pattern="${3:?fetch release: missing asset filename pattern}"
   local tag_format="${4:-v%s}"
 
   if [[ $version != 'latest' ]]; then
@@ -134,7 +156,7 @@ fetch_github_release() {
 }
 
 extract() {
-  local pkg="${1:?missing package name}" dest="${3:-/opt}"
+  local pkg="${1:?extract: missing package name}" dest="${3:-/opt}"
   tar -xf "$pkg" -C "$dest"
 }
 
@@ -149,6 +171,14 @@ main() {
         key) add_apt_key "$@" ;;
         source[_-]list) add_source_list "$@" ;;
         packages|package|pkgs|pkg) install_packages "$@" ;;
+        *) die 2 "invalid command 'add %s'" "$cmd"
+      esac
+      ;;
+    set)
+      cmd="${1:-}"; shift || :
+      case $cmd in
+        password|passwd|pass|pwd) set_password "$@" ;;
+        *) die 2 "invalid command 'set %s'" "$cmd"
       esac
       ;;
     download|fetch|get)
@@ -157,8 +187,14 @@ main() {
         *) fetch "$@"
       esac ;;
     extract) extract "$@" ;;
-    '') echo "love you"
+    die) die "$@" ;;
+    '') echo "${RED}love you${SGR0}" ;;
+    *) die 1 "invalid command '%s'" "$cmd"
   esac
 }
+
+if [[ ! -f /etc/debian_version ]]; then
+  die 8 "this script can be run in Debian-based distros only"
+fi
 
 main "$@"
